clone:
  git:
    submodule_override:
      tests/resource: https://gitee.com/khs1994-php/resource.git

workspace:
  base: /src
  path: .

pipeline:
  test:
    image: khs1994/php:7.2.10-fpm-alpine
    commands:
      - pwd
      - composer install -q
      # - composer update -q
      - vendor/bin/phpunit --coverage-clover=coverage.xml
      # set env CODECOV_TOKEN=XXX
      # - bash <(curl -s https://codecov.io/bash)
