clone:
  git:
    submodule_override:
      tests/resource: https://gitee.com/khs1994-php/resource.git

workspace:
  base: /src
  path: .

steps:
  test:
    image: khs1994/php:7.4.9-composer-alpine
    run:
      - pwd
      - composer install -q
      # - composer update -q
      - composer test:coverage
