language: php
# cache:
#   directories:
#   - vendor
php:
  # Not Support 7.0
  # - 7.0
  - 7.1
  - 7.2
script:
- composer self-update
- composer install -q
- composer update -q
- vendor/bin/phpunit
branches:
  only:
  - master
  - dev
