language: php
# cache:
#   directories:
#   - vendor
php:
  # - 5.6
  # - 7.0
  - 7.1
  - 7.2
script:
  - composer self-update
  - composer install -q
  # - composer update -q
  # - vendor/bin/phpunit --no-configuration --filter "/::testDeleteForce( .*)?$/" TencentAI\Tests\FaceTest $PWD/tests/TencentAI/FaceTest.php
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  # set env CODECOV_TOKEN=XXX
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
    - dev
