language: php
# cache:
#   directories:
#   - vendor
php:
  - 7.2.1
script:
- composer self-update
- composer install -q
- composer update -q
- vendor/bin/phpunit
branches:
  only:
  - master
  - dev
